server:
  port: 28888

custom:
  boot:
    iplist:
      enabled: true
      config-file: iplist.yaml
      refresh-interval: 10
    access-log:
      enabled: true
      config-file: logback-access.xml
    trace:
      enabled: true

logging:
  level:
    com.baidu.oped.sia.boot: DEBUG
