server:
  port: 28888

custom:
  boot:
    spring:
      fox:
        patterns:
          - /api**
          - /test**
        group-name: test-springfox-api
        api-info:
          title: Test SpringFox Api
          version: 10.0.1